version: '3'

services:
  rails:
    build:
      context: ./rails
      dockerfile: Dockerfile
    command: bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s
    ports:
      - 3000:3000
      - 1234:1234
      - 26162:26162
    volumes:
      - ./rails:/rails:cached
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: 'bridge'
  backend:
    driver: 'bridge'
